#!/bin/bash

function show_usage()
{
    printf "Usage: $0 <command>\n"
    cat <<EOF
    -u|--docker-compose-up
    -d|--docker-compose-down
    -c|--clean-all
    -s|--status
    -l|--login-to-sql-server
    -h|--help
EOF
  exit 1
}

if [[ $# -lt 1 ]]; then
    show_usage $@
fi

function docker_login_sql_server()
{
    docker-compose exec sqlserverdb bash
}

function docker_up()
{
    docker-compose up --detach
}

function docker_down()
{
    docker-compose down
}

function docker_clean_all()
{
    docker-compose rm -s -f
}

function docker_status()
{
    docker-compose ps -a
    docker-compose logs sqlserverdb | tail -30
}

function run_test_scripts()
{
    docker-compose exec -w /shared sqlserverdb ./run-test-scripts
}

while [[ $# -gt 0 ]]; do
  key="$1"

  case $key in
    -l|--login-sql-server)
        shift
        docker_login_sql_server
        ;;
    -u|--docker-compose-up)
        shift
        docker_up
        ;;
    -d|--docker-compose-down)
        shift
        docker_down
        ;;
    -c|--clean-all)
        shift
        docker_clean_all
        ;;
    -s|--status)
        shift
        docker_status
        ;;
    -t|--run-test-scripts)
        shift
        run_test_scripts
        ;;
    -h|--help)
        show_usage
      ;;
    *)    # unknown option
      POSITIONAL+=("$1") # save it in an array for later
      shift # past argument
      ;;
  esac
done
